# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: doros
description: A hardened Fedora Atomic KDE image for users with security and AI research in mind

base-image: ghcr.io/secureblue/kinoite-nvidia-open-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - enable-sshd-for-testing.sh

  - type: script
    scripts:
      - install-starship.sh

  - type: dnf
    install:
      packages:
        - micro
        - htop
        - btop
        - neovim

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
